base-sepolia:
  user-workflow:
    workflow-name: "mandinga-yield-harvest-base-sepolia"
  workflow-artifacts:
    workflow-path: "./index.ts"
    config-path: "./config.base-sepolia.json"
    secrets-path: ""

base-mainnet:
  user-workflow:
    workflow-name: "mandinga-yield-harvest-base-mainnet"
  workflow-artifacts:
    workflow-path: "./index.ts"
    config-path: "./config.base-mainnet.json"
    secrets-path: ""
